# Generated by Django 4.1.7 on 2023-03-03 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=200)),
                ('quartier', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], max_length=32)),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=100)),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('place', models.IntegerField(default=4)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='car_app.personne')),
                ('matricule', models.CharField(max_length=10)),
            ],
            bases=('car_app.personne',),
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='car_app.personne')),
                ('matricule', models.CharField(max_length=10)),
                ('type_poste', models.CharField(max_length=300)),
                ('type_personnel', models.CharField(choices=[('Gerant', 'Gerant'), ('Administrateur', 'Administrateur')], max_length=50)),
            ],
            bases=('car_app.personne',),
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('montant', models.FloatField()),
                ('date_commande', models.DateField(auto_now_add=True)),
                ('type_commande', models.CharField(choices=[('Achat', 'Achat'), ('Locations', 'Locations')], max_length=50)),
                ('id_voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.voiture')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.client')),
            ],
        ),
    ]
