# Generated by Django 4.1.7 on 2023-03-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='genre',
            field=models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin'), ('Autre', 'Autre')], max_length=32),
        ),
    ]
